apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apply-ingress
  namespace: apply-ns
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/apply(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: apply-svc
            port:
              number: 80
