apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: member-ingress
  namespace: member-ns
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/member(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: member-svc
            port:
              number: 80
